[package]
name = "block"
version = "0.1.0"
authors = ["datzero9 <nguyenmanhdat2903@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
diesel = { version = "1.4.0", features = ["postgres"] }
types = { path = "../types"}
plugins_core = { path = "../plugins-core" }
diesel_derive_table = { path = "../diesel-derive-table" }