[package]
name = "indexer"
version = "0.1.0"
authors = ["datzero9 <nguyenmanhdat2903@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.0", features = ["postgres"] }
common = { path = "../common"}